version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tasktracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: tasktracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-runtime
    container_name: tasktracker-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasktracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret123
      JWT_SECRET: SzuPerTitkosBiztonsagosKulcs123456!
      JWT_EXPIRATION: 3600000
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: tasktracker-frontend
    ports:
      - "8081:8081"
    working_dir: /app
    command: serve -s dist -l 8081
    depends_on:
      - backend

volumes:
  pgdata:
